package table11

// Table8 es una enumeración de tipo string
type Table8 string

const (
	LIBRO_1  Table8 = "1"
	LIBRO_2  Table8 = "2"
	LIBRO_3  Table8 = "3"
	LIBRO_4  Table8 = "4"
	LIBRO_5  Table8 = "5"
	LIBRO_6  Table8 = "6"
	LIBRO_7  Table8 = "7"
	LIBRO_8  Table8 = "8"
	LIBRO_9  Table8 = "9"
	LIBRO_10 Table8 = "10"
	LIBRO_11 Table8 = "11"
	LIBRO_12 Table8 = "12"
	LIBRO_13 Table8 = "13"
	LIBRO_14 Table8 = "14"
	LIBRO_15 Table8 = "15"
	LIBRO_16 Table8 = "16"
	LIBRO_17 Table8 = "17"
	LIBRO_18 Table8 = "18"
	LIBRO_19 Table8 = "19"
	LIBRO_20 Table8 = "20"
	LIBRO_21 Table8 = "21"
	LIBRO_22 Table8 = "22"
	LIBRO_23 Table8 = "23"
	LIBRO_24 Table8 = "24"
	LIBRO_25 Table8 = "25"
	LIBRO_26 Table8 = "26"
	LIBRO_27 Table8 = "27"
	LIBRO_28 Table8 = "28"
	LIBRO_29 Table8 = "29"
	LIBRO_30 Table8 = "30"
	LIBRO_31 Table8 = "31"
)

var Table8Items = map[Table8]string{
	LIBRO_1:  "LIBRO CAJA Y BANCOS",
	LIBRO_2:  "LIBRO DE INGRESOS Y GASTOS",
	LIBRO_3:  "LIBRO DE INVENTARIOS Y BALANCES",
	LIBRO_4:  "LIBRO DE RETENCIONES INCISOS E) Y F) DEL ARTICULO 34° DE LA LEY DEL IMPUESTO A LA RENTA",
	LIBRO_5:  "LIBRO DIARIO",
	LIBRO_6:  "LIBRO MAYOR",
	LIBRO_7:  "REGISTRO DE ACTIVOS FIJOS",
	LIBRO_8:  "REGISTRO DE COMPRAS",
	LIBRO_9:  "REGISTRO DE CONSIGNACIONES",
	LIBRO_10: "REGISTRO DE COSTOS",
	LIBRO_11: "REGISTRO DE HUÉSPEDES",
	LIBRO_12: "REGISTRO DE INVENTARIO PERMANENTE EN UNIDADES FÍSICAS",
	LIBRO_13: "REGISTRO DE INVENTARIO PERMANENTE VALORIZADO",
	LIBRO_14: "REGISTRO DE VENTAS E INGRESOS",
	LIBRO_15: "REGISTRO DE VENTAS E INGRESOS - ARTÍCULO 23° RESOLUCIÓN DE SUPERINTENDENCIA N° 266-2004/SUNAT",
	LIBRO_16: "REGISTRO DEL RÉGIMEN DE PERCEPCIONES",
	LIBRO_17: "REGISTRO DEL RÉGIMEN DE RETENCIONES",
	LIBRO_18: "REGISTRO IVAP",
	LIBRO_19: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - ARTÍCULO 8° RESOLUCIÓN DE SUPERINTENDENCIA N° 022-98/SUNAT",
	LIBRO_20: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 021-99/SUNAT",
	LIBRO_21: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 142-2001/SUNAT",
	LIBRO_22: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO C) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 256-2004/SUNAT",
	LIBRO_23: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 257-2004/SUNAT",
	LIBRO_24: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO C) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 258-2004/SUNAT",
	LIBRO_25: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 259-2004/SUNAT",
	LIBRO_26: "REGISTRO DE RETENCIONES ARTÍCULO 77-A DE LA LEY DEL IMPUESTO A LA RENTA",
	LIBRO_27: "LIBRO DE ACTAS DE LA EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA",
	LIBRO_28: "LIBRO DE ACTAS DE LA JUNTA GENERAL DE ACCIONISTAS",
	LIBRO_29: "LIBRO DE ACTAS DEL DIRECTORIO",
	LIBRO_30: "LIBRO DE MATRÍCULA DE ACCIONES",
	LIBRO_31: "LIBRO DE PLANILLAS",
}

// validateCode verifica si el código es válido dentro de Table8
func ValidateCode(code string) bool {
	for key := range Table8Items {
		if string(key) == code {
			return true
		}
	}
	return false
}

// getName devuelve el nombre correspondiente al valor
func GetName(code string) string {
	name, ok := Table8Items[Table8(code)]
	if !ok {
		return ""
	}
	return name
}
